### PR TITLE
feature - convert GoPiGo2's empathy bot project to work for the GoPiGo3

### PR DESCRIPTION
**Pull request by RobertLucian**
Make the Empathy Bot work again for the GoPiGo3 - replace imports, fix syntax errors, replace GoPiGo2 API with the one for the GoPiGo3.

It seems like it doesn't say anything about my face (don't know why), it keeps on coming with `UNLIKELY` and `VERY UNLIKELY` responses for each facial expression, but the JSON response looks valid to me, so I think this could be because of the lighting conditions.

### CODE REVIEW

**Comment by RobertLucian** [comment]
And as @CleoQc has pointed it, it can fail because I have a beard. So this can explain what I have described up top.

**Comment by johnisanerd** [comment]
Ah, the old "Beard Failure" mode.  The downside, #beardlife.

**Comment by CleoQc** [comment]
URL in readme is failing

**Comment by CleoQc** [comment]
Tutorial could use an update too. It talks of ultrasonic sensor instead of distance sensor, for example.

**Pull request merged**
