### PR TITLE
Fix for distance_sensor  (+ distance_sensor read_inches was returning a float)

### PR DESCRIPTION
**Pull request by CleoQc**
Now read_inches returning an integer as per the docs

Instantiating a distance sensor needs mutex protection.

### CODE REVIEW

**Comment by CleoQc** [comment]
@RobertLucian , 
read_inches for both ultrasonic and distance sensors have been changed to display one decimal.

**Comment by RobertLucian** [comment]
I can see lots of changes/additions here.
I've read them already and I also want to test the PR before accepting it.

**Comment by RobertLucian** [comment]
@CleoQc do we still need https://github.com/DexterInd/GoPiGo3/pull/96? I can see it's a subset of this PR.

**Comment by CleoQc** [comment]
If 96 gets merged first, this one will be a lot simpler

**Comment by CleoQc** [comment]
fixed the PR. Now 98

**Pull request closed without merging**
