### PR TITLE
Bring easygopigo3 in line with current firmware and gopigo3

### PR DESCRIPTION
**Pull request by CleoQc**
Handles the exceptions that may be raised from gopigo3.py

Major exceptions (like the GPG3 not being detected) are raised higher up. Others are handled at this level with a warning being printed but no tracebacks.

### CODE REVIEW

**Comment by RobertLucian** [comment]
@CleoQc I wasn't aware of the fact that these libraries can raise exceptions. I was more like on the impression that the `gopigo3.py` library handles all the exceptions.

Are these all the exceptions that can be encountered?
I'm asking this because I'm writing the documentation and I need to know all the bits, so I can document them too.

**Comment by CleoQc** [comment]
gopigo3 can raise more exceptions but in most cases they are already covered in easy Gopigo3

**Comment by CleoQc** [comment]
The only exceptions easygopigo3 is raising are in the init method. Once instantiated then it handles everything

**Comment by CleoQc** [comment]
@mattallen37 : I've done the changes you requested

**Pull request merged**
