### PR TITLE
Change the Java folder structure

### PR DESCRIPTION
**Pull request by CleoQc**
Move all files up a folder.

### CODE REVIEW

**Comment by jabrena** [comment]
It has sense.

**Comment by CleoQc** [comment]
@jabrena  are there any paths in the code that might suffer from this change? I didn't take a look as Java is not part of my current knowledge.

**Comment by jabrena** [comment]
No, don´t worry. It is a simple change. You can do with confident. :)

**Comment by CleoQc** [comment]
Thank you so much for the sanity check :)

**Comment by jabrena** [comment]
Make any question, I will help. :)

**Pull request merged**
